version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: true
  skip-dirs:
    - vendor
    - generated
  issues-exit-code: 1

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - misspell
    # enable when useful:
    # - gosec
    # - nilaway
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - os.Remove
        - (*github.com/iley/pirx/internal/parser.Parser).consume

formatters:
  enable:
    - gofumpt
    - goimports
